ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'cats#index'
  resources :cats,  only: [:index, :show, :create, :update, :edit, :new]
  
end

ninety-nine-cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ninety-nine-cats/app/models/cat.rb
require "action_view"


class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    COLORS = ['cream','black','white']
    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: { in: COLORS}
    validates :sex, inclusion: { in: ['M', 'F']}

    validate :birth_date_cannot_be_future
    

    def birth_date_cannot_be_future
        if birth_date.present? && birth_date > Date.today
            errors.add(:birth_date, "can't be in the future")
        end
      
    end
end

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find_by(id: params[:id])
        if @cat
            render :show
        else
            @cat.errors.full_messages, status_code = 422
        end
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat && @cat.save!
            redirect_to cat_url(@cat)
        else
            render @cat.errors.full_messages, status_code: 422
        end
    end

    def edit
        @user = User.find_by(id: params[:id])
        render :edit
    end

    def new
        @cat = Cat.new
        render :new
    end

    def update
    end
    
    private 
    def cat_params
        params.require(:cat).permit(:sex, :color, :name, :birth_date)
    end
    

end

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/helpers/cats_helper.rb
module CatsHelper
end

ninety-nine-cats/app/views/cats/edit.html.erb
<form action="<%= cats_url %>" method="post" >
<label >select gender:
<br>
<label >Male:
<input type="radio" name="cat[sex]" value="M" >
<br>
<label >Female:
<input type="radio" name="cat[sex]" value="F" >

<br>
<br>
<select  name="cat[color]" value="">
 <option disabled selected value> -- select an option -- </option>
<% Cat::COLORS.each do |color|%>
<option value="<%= color%>"> "<%= color %>"</option>
<% end%>
</select>
<br>
<br>
<input name="cat[name]" type="text">
<br>
<br>
<label>Start date:</label>
<input type="date" name="cat[birth_date]"
       value="2018-07-22"
       min="2018-01-01" max="2022-12-31">
       

<input type="submit" value="Update Cat" >

</form>

ninety-nine-cats/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post" >
<input type="radio" name="cat[sex]" value="<%= @cat.sex%>" >
<select  name="cat[color]" value=value="<%= @cat.color%>">
<% Cat::COLORS.each do |color|%>
<option value="<%= color%>"> "<%= color %>"</option>
<% end%>
</select>
</form>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>